In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("winequality-white.csv", sep=";")

In [3]:
df.head()

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality
0,7.0,0.27,0.36,20.7,0.045,45.0,170.0,1.0010,3.00,0.45,8.8,6
1,6.3,0.30,0.34,1.6,0.049,14.0,132.0,0.9940,3.30,0.49,9.5,6
2,8.1,0.28,0.40,6.9,0.050,30.0,97.0,0.9951,3.26,0.44,10.1,6
3,7.2,0.23,0.32,8.5,0.058,47.0,186.0,0.9956,3.19,0.40,9.9,6
4,7.2,0.23,0.32,8.5,0.058,47.0,186.0,0.9956,3.19,0.40,9.9,6

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4898 entries, 0 to 4897
Data columns (total 12 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   fixed acidity         4898 non-null   float64
 1   volatile acidity      4898 non-null   float64
 2   citric acid           4898 non-null   float64
 3   residual sugar        4898 non-null   float64
 4   chlorides             4898 non-null   float64
 5   free sulfur dioxide   4898 non-null   float64
 6   total sulfur dioxide  4898 non-null   float64
 7   density               4898 non-null   float64
 8   pH                    4898 non-null   float64
 9   sulphates             4898 non-null   float64
 10  alcohol               4898 non-null   float64
 11  quality               4898 non-null   int64
dtypes: float64(11), int64(1)
memory usage: 459.3 KB

In [5]:
df.describe()

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality
count,4898.000000,4898.000000,4898.000000,4898.000000,4898.000000,4898.000000,4898.000000,4898.000000,4898.000000,4898.000000,4898.000000,4898.000000
mean,6.854788,0.278241,0.334192,6.391415,0.045772,35.308085,138.360657,0.994027,3.188267,0.489847,10.514267,5.877909
std,0.843868,0.100795,0.121020,5.072058,0.021848,17.007137,42.498065,0.002991,0.151001,0.114126,1.230621,0.885639
min,3.800000,0.080000,0.000000,0.600000,0.009000,2.000000,9.000000,0.987110,2.720000,0.220000,8.000000,3.000000
25%,6.300000,0.210000,0.270000,1.700000,0.036000,23.000000,108.000000,0.991723,3.090000,0.410000,9.500000,5.000000
50%,6.800000,0.260000,0.320000,5.200000,0.043000,34.000000,134.000000,0.993740,3.180000,0.470000,10.400000,6.000000
75%,7.300000,0.320000,0.390000,9.900000,0.050000,46.000000,167.000000,0.996100,3.280000,0.550000,11.400000,6.000000
max,14.200000,1.100000,1.660000,65.800000,0.346000,289.000000,440.000000,1.038980,3.820000,1.080000,14.200000,9.000000

In [6]:
df.columns

Index(['fixed acidity', 'volatile acidity', 'citric acid', 'residual sugar',
       'chlorides', 'free sulfur dioxide', 'total sulfur dioxide', 'density',
       'pH', 'sulphates', 'alcohol', 'quality'],
      dtype='object')

In [7]:
X = df[['fixed acidity', 'volatile acidity', 'citric acid', 'residual sugar',
       'chlorides', 'free sulfur dioxide', 'total sulfur dioxide', 'density',
       'pH', 'sulphates', 'alcohol']]
y = df['quality']

In [8]:
from sklearn.model_selection import train_test_split

In [9]:
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state = 2529)

In [10]:
from sklearn.neural_network import MLPClassifier

In [34]:
model = MLPClassifier(hidden_layer_sizes = (6,), max_iter = 5000, verbose = True)

In [35]:
model.fit(X_train, y_train)

Iteration 1, loss = 27.52000658
Iteration 2, loss = 25.14385055
Iteration 3, loss = 21.44545366
Iteration 4, loss = 17.58629689
Iteration 5, loss = 14.07839100
Iteration 6, loss = 11.08229175
Iteration 7, loss = 8.84110206
Iteration 8, loss = 7.41441933
Iteration 9, loss = 6.24242949
Iteration 10, loss = 5.16611897
Iteration 11, loss = 4.16225655
Iteration 12, loss = 3.28606255
Iteration 13, loss = 2.60097566
Iteration 14, loss = 2.23698088
Iteration 15, loss = 2.08030743
Iteration 16, loss = 2.00306069
Iteration 17, loss = 1.95005956
Iteration 18, loss = 1.90382033
Iteration 19, loss = 1.86264229
Iteration 20, loss = 1.82380586
Iteration 21, loss = 1.78811037
Iteration 22, loss = 1.75368148
Iteration 23, loss = 1.72225560
Iteration 24, loss = 1.69298780
Iteration 25, loss = 1.66552599
Iteration 26, loss = 1.63982956
Iteration 27, loss = 1.61556165
Iteration 28, loss = 1.59348051
Iteration 29, loss = 1.57194913
Iteration 30, loss = 1.55261116
Iteration 31, loss = 1.53315050
Iteration 32, loss = 1.51584127
Iteration 33, loss = 1.49949956
Iteration 34, loss = 1.48502610
Iteration 35, loss = 1.47202472
Iteration 36, loss = 1.45892853
Iteration 37, loss = 1.44709205
Iteration 38, loss = 1.43642448
Iteration 39, loss = 1.42603319
Iteration 40, loss = 1.41663699
Iteration 41, loss = 1.40791943
Iteration 42, loss = 1.39982807
Iteration 43, loss = 1.39417262
Iteration 44, loss = 1.38540729
Iteration 45, loss = 1.38003848
Iteration 46, loss = 1.37360885
Iteration 47, loss = 1.36790186
Iteration 48, loss = 1.36183704
Iteration 49, loss = 1.35678291
Iteration 50, loss = 1.35495243
Iteration 51, loss = 1.34777126
Iteration 52, loss = 1.34356692
Iteration 53, loss = 1.34068488
Iteration 54, loss = 1.33729255
Iteration 55, loss = 1.33436994
Iteration 56, loss = 1.33046768
Iteration 57, loss = 1.32967670
Iteration 58, loss = 1.32575906
Iteration 59, loss = 1.32068952
Iteration 60, loss = 1.31794572
Iteration 61, loss = 1.31483699
Iteration 62, loss = 1.31394460
Iteration 63, loss = 1.31265283
Iteration 64, loss = 1.30821418
Iteration 65, loss = 1.30860163
Iteration 66, loss = 1.30286714
Iteration 67, loss = 1.30188230
Iteration 68, loss = 1.29977930
Iteration 69, loss = 1.29830995
Iteration 70, loss = 1.29647444
Iteration 71, loss = 1.29557183
Iteration 72, loss = 1.29420123
Iteration 73, loss = 1.29291033
Iteration 74, loss = 1.29058492
Iteration 75, loss = 1.28875482
Iteration 76, loss = 1.28772360
Iteration 77, loss = 1.28570473
Iteration 78, loss = 1.28455454
Iteration 79, loss = 1.28396382
Iteration 80, loss = 1.28343500
Iteration 81, loss = 1.28183912
Iteration 82, loss = 1.28150298
Iteration 83, loss = 1.27903662
Iteration 84, loss = 1.28027734
Iteration 85, loss = 1.27883718
Iteration 86, loss = 1.27889194
Iteration 87, loss = 1.28089563
Iteration 88, loss = 1.27501709
Iteration 89, loss = 1.27352986
Iteration 90, loss = 1.27388725
Iteration 91, loss = 1.27306337
Iteration 92, loss = 1.27103106
Iteration 93, loss = 1.27122576
Iteration 94, loss = 1.27119155
Iteration 95, loss = 1.27014039
Iteration 96, loss = 1.27062236
Iteration 97, loss = 1.26978009
Iteration 98, loss = 1.26737317
Iteration 99, loss = 1.26720747
Iteration 100, loss = 1.26802241
Iteration 101, loss = 1.26668258
Iteration 102, loss = 1.26584188
Iteration 103, loss = 1.26729829
Iteration 104, loss = 1.26750296
Iteration 105, loss = 1.26369019
Iteration 106, loss = 1.26284445
Iteration 107, loss = 1.26331076
Iteration 108, loss = 1.26222124
Iteration 109, loss = 1.26278151
Iteration 110, loss = 1.26420279
Iteration 111, loss = 1.26274176
Iteration 112, loss = 1.26121118
Iteration 113, loss = 1.25937748
Iteration 114, loss = 1.25898561
Iteration 115, loss = 1.25952617
Iteration 116, loss = 1.25895672
Iteration 117, loss = 1.25899412
Iteration 118, loss = 1.25998858
Iteration 119, loss = 1.25858342
Iteration 120, loss = 1.25668661
Iteration 121, loss = 1.25538810
Iteration 122, loss = 1.25513992
Iteration 123, loss = 1.25541370
Iteration 124, loss = 1.25501902
Iteration 125, loss = 1.25469512
Iteration 126, loss = 1.25284369
Iteration 127, loss = 1.25272165
Iteration 128, loss = 1.25287821
Iteration 129, loss = 1.25177884
Iteration 130, loss = 1.25138865
Iteration 131, loss = 1.25236794
Iteration 132, loss = 1.25417238
Iteration 133, loss = 1.25130518
Iteration 134, loss = 1.24952769
Iteration 135, loss = 1.24891069
Iteration 136, loss = 1.24895430
Iteration 137, loss = 1.24964741
Iteration 138, loss = 1.24753746
Iteration 139, loss = 1.24753077
Iteration 140, loss = 1.24764374
Iteration 141, loss = 1.24666697
Iteration 142, loss = 1.24773657
Iteration 143, loss = 1.24628632
Iteration 144, loss = 1.24569635
Iteration 145, loss = 1.24608416
Iteration 146, loss = 1.24670505
Iteration 147, loss = 1.24446208
Iteration 148, loss = 1.24268952
Iteration 149, loss = 1.24529900
Iteration 150, loss = 1.24780705
Iteration 151, loss = 1.24441319
Iteration 152, loss = 1.24632457
Iteration 153, loss = 1.24309511
Iteration 154, loss = 1.24319217
Iteration 155, loss = 1.24251418
Iteration 156, loss = 1.24013506
Iteration 157, loss = 1.24049468
Iteration 158, loss = 1.23921423
Iteration 159, loss = 1.23868462
Iteration 160, loss = 1.24097322
Iteration 161, loss = 1.23834295
Iteration 162, loss = 1.23778964
Iteration 163, loss = 1.23621271
Iteration 164, loss = 1.23708105
Iteration 165, loss = 1.23631600
Iteration 166, loss = 1.23867957
Iteration 167, loss = 1.23522331
Iteration 168, loss = 1.23403113
Iteration 169, loss = 1.23435311
Iteration 170, loss = 1.24189611
Iteration 171, loss = 1.23271380
Iteration 172, loss = 1.23206471
Iteration 173, loss = 1.23332194
Iteration 174, loss = 1.23246065
Iteration 175, loss = 1.23159441
Iteration 176, loss = 1.23139359
Iteration 177, loss = 1.23314875
Iteration 178, loss = 1.23108355
Iteration 179, loss = 1.23214169
Iteration 180, loss = 1.23369892
Iteration 181, loss = 1.23306693
Iteration 182, loss = 1.23375445
Iteration 183, loss = 1.23486368
Iteration 184, loss = 1.22891634
Iteration 185, loss = 1.22888241
Iteration 186, loss = 1.22757654
Iteration 187, loss = 1.22744825
Iteration 188, loss = 1.23289501
Iteration 189, loss = 1.22811441
Iteration 190, loss = 1.22712081
Iteration 191, loss = 1.22878031
Iteration 192, loss = 1.23450481
Iteration 193, loss = 1.22431131
Iteration 194, loss = 1.22380464
Iteration 195, loss = 1.22782501
Iteration 196, loss = 1.22424391
Iteration 197, loss = 1.22389038
Iteration 198, loss = 1.22275508
Iteration 199, loss = 1.22353844
Iteration 200, loss = 1.22540860
Iteration 201, loss = 1.22405967
Iteration 202, loss = 1.22122562
Iteration 203, loss = 1.22172753
Iteration 204, loss = 1.21890717
Iteration 205, loss = 1.22237451
Iteration 206, loss = 1.22128814
Iteration 207, loss = 1.21932272
Iteration 208, loss = 1.22418944
Iteration 209, loss = 1.22206427
Iteration 210, loss = 1.21957957
Iteration 211, loss = 1.21812653
Iteration 212, loss = 1.21753174
Iteration 213, loss = 1.21697627
Iteration 214, loss = 1.22296175
Iteration 215, loss = 1.22109936
Iteration 216, loss = 1.21602701
Iteration 217, loss = 1.21938271
Iteration 218, loss = 1.21893133
Iteration 219, loss = 1.21716403
Iteration 220, loss = 1.21440853
Iteration 221, loss = 1.21463419
Iteration 222, loss = 1.21583164
Iteration 223, loss = 1.21368053
Iteration 224, loss = 1.21681694
Iteration 225, loss = 1.21490873
Iteration 226, loss = 1.21273710
Iteration 227, loss = 1.21244226
Iteration 228, loss = 1.21140628
Iteration 229, loss = 1.21243678
Iteration 230, loss = 1.21266971
Iteration 231, loss = 1.21105935
Iteration 232, loss = 1.20996767
Iteration 233, loss = 1.21275269
Iteration 234, loss = 1.21471315
Iteration 235, loss = 1.21390999
Iteration 236, loss = 1.20931509
Iteration 237, loss = 1.21055575
Iteration 238, loss = 1.20829345
Iteration 239, loss = 1.21264013
Iteration 240, loss = 1.20983654
Iteration 241, loss = 1.20912578
Iteration 242, loss = 1.20839486
Iteration 243, loss = 1.20780447
Iteration 244, loss = 1.20805305
Iteration 245, loss = 1.21161302
Iteration 246, loss = 1.21005674
Iteration 247, loss = 1.20729521
Iteration 248, loss = 1.20477991
Iteration 249, loss = 1.20786518
Iteration 250, loss = 1.20616344
Iteration 251, loss = 1.20681594
Iteration 252, loss = 1.20381596
Iteration 253, loss = 1.20328488
Iteration 254, loss = 1.20332096
Iteration 255, loss = 1.20304156
Iteration 256, loss = 1.20313714
Iteration 257, loss = 1.20221144
Iteration 258, loss = 1.20031358
Iteration 259, loss = 1.20150664
Iteration 260, loss = 1.20698213
Iteration 261, loss = 1.20732806
Iteration 262, loss = 1.20208029
Iteration 263, loss = 1.20143142
Iteration 264, loss = 1.20626992
Iteration 265, loss = 1.19950949
Iteration 266, loss = 1.19939210
Iteration 267, loss = 1.19930089
Iteration 268, loss = 1.20017656
Iteration 269, loss = 1.20424488
Iteration 270, loss = 1.19869186
Iteration 271, loss = 1.19822479
Iteration 272, loss = 1.20213974
Iteration 273, loss = 1.19710851
Iteration 274, loss = 1.19584042
Iteration 275, loss = 1.19841009
Iteration 276, loss = 1.19724563
Iteration 277, loss = 1.19657561
Iteration 278, loss = 1.19507731
Iteration 279, loss = 1.19560999
Iteration 280, loss = 1.19347521
Iteration 281, loss = 1.19223159
Iteration 282, loss = 1.19369277
Iteration 283, loss = 1.19260866
Iteration 284, loss = 1.19344707
Iteration 285, loss = 1.19432568
Iteration 286, loss = 1.19438888
Iteration 287, loss = 1.19303383
Iteration 288, loss = 1.19178210
Iteration 289, loss = 1.19328059
Iteration 290, loss = 1.19139367
Iteration 291, loss = 1.18958818
Iteration 292, loss = 1.18898564
Iteration 293, loss = 1.19027261
Iteration 294, loss = 1.19250316
Iteration 295, loss = 1.18901046
Iteration 296, loss = 1.18759348
Iteration 297, loss = 1.18917806
Iteration 298, loss = 1.19040424
Iteration 299, loss = 1.18847908
Iteration 300, loss = 1.18898445
Iteration 301, loss = 1.18962134
Iteration 302, loss = 1.18701453
Iteration 303, loss = 1.19048424
Iteration 304, loss = 1.18934490
Iteration 305, loss = 1.18585925
Iteration 306, loss = 1.18579167
Iteration 307, loss = 1.19047513
Iteration 308, loss = 1.18383245
Iteration 309, loss = 1.18420594
Iteration 310, loss = 1.18730610
Iteration 311, loss = 1.18388148
Iteration 312, loss = 1.18365580
Iteration 313, loss = 1.18160790
Iteration 314, loss = 1.18585757
Iteration 315, loss = 1.18336957
Iteration 316, loss = 1.18390243
Iteration 317, loss = 1.18449306
Iteration 318, loss = 1.18004202
Iteration 319, loss = 1.18393543
Iteration 320, loss = 1.18601730
Iteration 321, loss = 1.18273166
Iteration 322, loss = 1.17846900
Iteration 323, loss = 1.18166145
Iteration 324, loss = 1.18030704
Iteration 325, loss = 1.18083114
Iteration 326, loss = 1.17641708
Iteration 327, loss = 1.17794212
Iteration 328, loss = 1.17748106
Iteration 329, loss = 1.18282664
Iteration 330, loss = 1.18151321
Iteration 331, loss = 1.18147877
Iteration 332, loss = 1.17558215
Iteration 333, loss = 1.17621515
Iteration 334, loss = 1.18222371
Iteration 335, loss = 1.18032977
Iteration 336, loss = 1.17515163
Iteration 337, loss = 1.17421674
Iteration 338, loss = 1.17436562
Iteration 339, loss = 1.17827747
Iteration 340, loss = 1.17374415
Iteration 341, loss = 1.17162904
Iteration 342, loss = 1.17216262
Iteration 343, loss = 1.17551352
Iteration 344, loss = 1.17320534
Iteration 345, loss = 1.16995574
Iteration 346, loss = 1.17385818
Iteration 347, loss = 1.17523680
Iteration 348, loss = 1.16960616
Iteration 349, loss = 1.17116312
Iteration 350, loss = 1.16746883
Iteration 351, loss = 1.17365876
Iteration 352, loss = 1.16847173
Iteration 353, loss = 1.16937763
Iteration 354, loss = 1.16773660
Iteration 355, loss = 1.16712277
Iteration 356, loss = 1.16652434
Iteration 357, loss = 1.16846948
Iteration 358, loss = 1.16478049
Iteration 359, loss = 1.16593808
Iteration 360, loss = 1.16642587
Iteration 361, loss = 1.16688223
Iteration 362, loss = 1.16516797
Iteration 363, loss = 1.16432176
Iteration 364, loss = 1.16334176
Iteration 365, loss = 1.16266670
Iteration 366, loss = 1.16483434
Iteration 367, loss = 1.16186939
Iteration 368, loss = 1.16172336
Iteration 369, loss = 1.16115399
Iteration 370, loss = 1.16695493
Iteration 371, loss = 1.16534116
Iteration 372, loss = 1.16826474
Iteration 373, loss = 1.16449925
Iteration 374, loss = 1.16571190
Iteration 375, loss = 1.16686612
Iteration 376, loss = 1.16084634
Iteration 377, loss = 1.15927571
Iteration 378, loss = 1.15788148
Iteration 379, loss = 1.15649711
Iteration 380, loss = 1.15962322
Iteration 381, loss = 1.15732514
Iteration 382, loss = 1.15783900
Iteration 383, loss = 1.16336112
Iteration 384, loss = 1.16396800
Iteration 385, loss = 1.15855663
Iteration 386, loss = 1.15742273
Iteration 387, loss = 1.15986461
Iteration 388, loss = 1.15955693
Iteration 389, loss = 1.15412117
Iteration 390, loss = 1.15537362
Iteration 391, loss = 1.15699348
Iteration 392, loss = 1.16423269
Iteration 393, loss = 1.15598475
Iteration 394, loss = 1.15096229
Iteration 395, loss = 1.15116708
Iteration 396, loss = 1.15119891
Iteration 397, loss = 1.15116059
Iteration 398, loss = 1.14892843
Iteration 399, loss = 1.15617230
Iteration 400, loss = 1.15044616
Iteration 401, loss = 1.15704791
Iteration 402, loss = 1.15108253
Iteration 403, loss = 1.14847100
Iteration 404, loss = 1.15212845
Iteration 405, loss = 1.14774518
Iteration 406, loss = 1.14793294
Iteration 407, loss = 1.15154060
Iteration 408, loss = 1.15140914
Iteration 409, loss = 1.14746354
Iteration 410, loss = 1.14749111
Iteration 411, loss = 1.14551981
Iteration 412, loss = 1.15338395
Iteration 413, loss = 1.14722021
Iteration 414, loss = 1.14816950
Iteration 415, loss = 1.14743170
Iteration 416, loss = 1.14830261
Iteration 417, loss = 1.14927695
Iteration 418, loss = 1.14884015
Iteration 419, loss = 1.14704457
Iteration 420, loss = 1.14398873
Iteration 421, loss = 1.14395430
Iteration 422, loss = 1.14737449
Iteration 423, loss = 1.14068094
Iteration 424, loss = 1.14093654
Iteration 425, loss = 1.14439983
Iteration 426, loss = 1.14597927
Iteration 427, loss = 1.14352058
Iteration 428, loss = 1.14002009
Iteration 429, loss = 1.14459877
Iteration 430, loss = 1.13978877
Iteration 431, loss = 1.13916163
Iteration 432, loss = 1.14247097
Iteration 433, loss = 1.13893842
Iteration 434, loss = 1.14064480
Iteration 435, loss = 1.13955194
Iteration 436, loss = 1.14139194
Iteration 437, loss = 1.13972111
Iteration 438, loss = 1.13980925
Iteration 439, loss = 1.13750578
Iteration 440, loss = 1.13616797
Iteration 441, loss = 1.14049301
Iteration 442, loss = 1.13838600
Iteration 443, loss = 1.13830646
Iteration 444, loss = 1.13782163
Iteration 445, loss = 1.13613977
Iteration 446, loss = 1.13749806
Iteration 447, loss = 1.13530012
Iteration 448, loss = 1.13363825
Iteration 449, loss = 1.13730333
Iteration 450, loss = 1.13415685
Iteration 451, loss = 1.13509618
Iteration 452, loss = 1.13658542
Iteration 453, loss = 1.13662881
Iteration 454, loss = 1.13960390
Iteration 455, loss = 1.13251548
Iteration 456, loss = 1.13524364
Iteration 457, loss = 1.13352532
Iteration 458, loss = 1.14208275
Iteration 459, loss = 1.13530346
Iteration 460, loss = 1.13127938
Iteration 461, loss = 1.13283083
Iteration 462, loss = 1.13048758
Iteration 463, loss = 1.13702562
Iteration 464, loss = 1.13273609
Iteration 465, loss = 1.13215006
Iteration 466, loss = 1.12991558
Iteration 467, loss = 1.13059374
Iteration 468, loss = 1.13455018
Iteration 469, loss = 1.13067329
Iteration 470, loss = 1.13064862
Iteration 471, loss = 1.12821780
Iteration 472, loss = 1.13654334
Iteration 473, loss = 1.13196772
Iteration 474, loss = 1.12868685
Iteration 475, loss = 1.12775006
Iteration 476, loss = 1.12920192
Iteration 477, loss = 1.13314271
Iteration 478, loss = 1.13018191
Iteration 479, loss = 1.12718783
Iteration 480, loss = 1.12571807
Iteration 481, loss = 1.12724894
Iteration 482, loss = 1.12946442
Iteration 483, loss = 1.13410498
Iteration 484, loss = 1.12751237
Iteration 485, loss = 1.12687361
Iteration 486, loss = 1.13151963
Iteration 487, loss = 1.12524637
Iteration 488, loss = 1.12906858
Iteration 489, loss = 1.12427285
Iteration 490, loss = 1.12702349
Iteration 491, loss = 1.12623494
Iteration 492, loss = 1.12374009
Iteration 493, loss = 1.12661085
Iteration 494, loss = 1.12387709
Iteration 495, loss = 1.12697949
Iteration 496, loss = 1.12504536
Iteration 497, loss = 1.12830876
Iteration 498, loss = 1.12549312
Iteration 499, loss = 1.12382813
Iteration 500, loss = 1.12438250
Iteration 501, loss = 1.12599089
Iteration 502, loss = 1.12368994
Iteration 503, loss = 1.12629121
Training loss did not improve more than tol=0.000100 for 10 consecutive epochs. Stopping.

MLPClassifier(hidden_layer_sizes=(6,), max_iter=5000, verbose=True)

In [36]:
y_predict = model.predict(X_test)

In [37]:
from sklearn.metrics import mean_absolute_percentage_error

In [38]:
error = mean_absolute_percentage_error(y_test, y_predict)

In [39]:
error * 100

9.232361516034985