In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("https://raw.githubusercontent.com/YBI-Foundation/Dataset/refs/heads/main/Air%20Quality%20Missing%20Data.csv")

In [3]:
df.head()

         Date  Ozone  Solar  Wind  Temp
0  01-05-1976   41.0  190.0   7.4    67
1  02-05-1976   36.0  118.0   8.0    72
2  03-05-1976   12.0  149.0  12.6    74
3  04-05-1976   18.0  313.0  11.5    62
4  05-05-1976    NaN    NaN  14.3    56

In [5]:
df.describe()

            Ozone       Solar        Wind        Temp
count  116.000000  146.000000  153.000000  153.000000
mean    42.129310  185.931507    9.957516   77.882353
std     32.987885   90.058422    3.523001    9.465270
min      1.000000    7.000000    1.700000   56.000000
25%     18.000000  115.750000    7.400000   72.000000
50%     31.500000  205.000000    9.700000   79.000000
75%     63.250000  258.750000   11.500000   85.000000
max    168.000000  334.000000   20.700000   97.000000

In [14]:
df.isna().sum()

Date      0
Ozone    37
Solar     7
Wind      0
Temp      0
dtype: int64

In [15]:
df = df.dropna()

In [17]:
df.isna().sum()

Date     0
Ozone    0
Solar    0
Wind     0
Temp     0
dtype: int64

In [18]:
df.columns

Index(['Date', 'Ozone', 'Solar', 'Wind', 'Temp'], dtype='object')

In [19]:
X = df[['Ozone', 'Solar', 'Wind']]
y = df['Temp']

In [20]:
from sklearn.model_selection import train_test_split

In [21]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 2529)

In [50]:
# 1.
# from sklearn.naive_bayes import GaussianNB
# model = GaussianNB()

# 2.
# from sklearn.neighbors import KNeighborsClassifier
# model = KNeighborsClassifier()

# from sklearn.neighbors import KNeighborsRegressor
# model = KNeighborsRegressor()

# 3.
# from sklearn.tree import DecisionTreeClassifier
# model = DecisionTreeClassifier(criterion = "entropy")

# 4.
# from sklearn.tree import DecisionTreeClassifier
# model = DecisionTreeClassifier(criterion = "entropy", min_samples_split = 5, min_impurity_decrease = 0.01)

# from sklearn.tree import DecisionTreeRegressor
# model = DecisionTreeRegressor()

# 5.
# from sklearn.linear_model import LogisticRegression
# model = LogisticRegression(max_iter = 5000)

# 6.
# from sklearn.neural_network import MLPClassifier
# model = MLPClassifier(hidden_layer_sizes = (8,), max_iter = 5000)

# 7.
# from sklearn.ensemble import VotingClassifier
# from sklearn.linear_model import LogisticRegression
# from sklearn.neighbors import KNeighborsClassifier
# from sklearn.tree import DecisionTreeClassifier
# model_1 = LogisticRegression(max_iter = 5000)
# model_2 = KNeighborsClassifier()
# model_3 = DecisionTreeClassifier()
# model = VotingClassifier(estimators = [("lr", model_1), ("knn", model_2), ("dt", model_3)], voting = "soft")

# 8.
# from sklearn.ensemble import RandomForestClassifier
# model = RandomForestClassifier()

# from sklearn.ensemble import RandomForestRegressor
# model = RandomForestRegressor()

# 9.
# from sklearn.ensemble import AdaBoostClassifier
# model = AdaBoostClassifier()

from sklearn.ensemble import AdaBoostRegressor
model = AdaBoostRegressor()

In [51]:
model.fit(X_train, y_train)

AdaBoostRegressor()

In [52]:
y_pred = model.predict(X_test)

In [53]:
from sklearn.metrics import mean_absolute_percentage_error

In [54]:
error = mean_absolute_percentage_error(y_test, y_pred)

In [55]:
error * 100

6.530562547553142