In [67]:
import pandas as pd

In [68]:
df = pd.read_csv("digits.csv")

In [69]:
df.head()

,label,pixel0,pixel1,pixel2,pixel3,pixel4,pixel5,pixel6,pixel7,pixel8,...,pixel774,pixel775,pixel776,pixel777,pixel778,pixel779,pixel780,pixel781,pixel782,pixel783
0,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,4,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [70]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 42000 entries, 0 to 41999
Columns: 785 entries, label to pixel783
dtypes: int64(785)
memory usage: 251.5 MB

In [71]:
df.describe()

,label,pixel0,pixel1,pixel2,pixel3,pixel4,pixel5,pixel6,pixel7,pixel8,...,pixel774,pixel775,pixel776,pixel777,pixel778,pixel779,pixel780,pixel781,pixel782,pixel783
count,42000.000000,42000.0,42000.0,42000.0,42000.0,42000.0,42000.0,42000.0,42000.0,42000.0,...,42000.000000,42000.000000,42000.000000,42000.00000,42000.000000,42000.000000,42000.0,42000.0,42000.0,42000.0
mean,4.456643,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.219286,0.117095,0.059024,0.02019,0.017238,0.002857,0.0,0.0,0.0,0.0
std,2.887730,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,6.312890,4.633819,3.274488,1.75987,1.894498,0.414264,0.0,0.0,0.0,0.0
min,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.0,0.0,0.0,0.0
25%,2.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.0,0.0,0.0,0.0
50%,4.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.0,0.0,0.0,0.0
75%,7.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.0,0.0,0.0,0.0
max,9.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,254.000000,254.000000,253.000000,253.00000,254.000000,62.000000,0.0,0.0,0.0,0.0

In [72]:
df.columns

Index(['label', 'pixel0', 'pixel1', 'pixel2', 'pixel3', 'pixel4', 'pixel5',
       'pixel6', 'pixel7', 'pixel8',
       ...
       'pixel774', 'pixel775', 'pixel776', 'pixel777', 'pixel778', 'pixel779',
       'pixel780', 'pixel781', 'pixel782', 'pixel783'],
      dtype='object', length=785)

In [73]:
X = df[[f"pixel{i}" for i in range(784)]]
y = df["label"]

In [74]:
from sklearn.model_selection import train_test_split

In [75]:
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state = 2529)

In [76]:
from sklearn.neural_network import MLPClassifier

In [ ]:
model = MLPClassifier(hidden_layer_sizes = (16,), max_iter = 500, verbose = True)

In [90]:
model.fit(X_train, y_train)

Iteration 1, loss = 4.34728385
Iteration 2, loss = 2.00710527
Iteration 3, loss = 1.82111497
Iteration 4, loss = 1.73344618
Iteration 5, loss = 1.67307409
Iteration 6, loss = 1.62471780
Iteration 7, loss = 1.54119981
Iteration 8, loss = 1.39865842
Iteration 9, loss = 1.22941189
Iteration 10, loss = 1.06396503
Iteration 11, loss = 0.97233841
Iteration 12, loss = 0.89430963
Iteration 13, loss = 0.83302008
Iteration 14, loss = 0.77048280
Iteration 15, loss = 0.72600961
Iteration 16, loss = 0.67807015
Iteration 17, loss = 0.65097361
Iteration 18, loss = 0.62041548
Iteration 19, loss = 0.59386151
Iteration 20, loss = 0.56888123
Iteration 21, loss = 0.55026895
Iteration 22, loss = 0.52599357
Iteration 23, loss = 0.51336193
Iteration 24, loss = 0.48756076
Iteration 25, loss = 0.46689717
Iteration 26, loss = 0.43856318
Iteration 27, loss = 0.42321417
Iteration 28, loss = 0.40552233
Iteration 29, loss = 0.39496328
Iteration 30, loss = 0.38060667
Iteration 31, loss = 0.37509031
Iteration 32, loss = 0.36582313
Iteration 33, loss = 0.35070727
Iteration 34, loss = 0.35331852
Iteration 35, loss = 0.33570712
Iteration 36, loss = 0.33195115
Iteration 37, loss = 0.32583526
Iteration 38, loss = 0.31921649
Iteration 39, loss = 0.31199174
Iteration 40, loss = 0.31241942
Iteration 41, loss = 0.30928012
Iteration 42, loss = 0.30100990
Iteration 43, loss = 0.29144017
Iteration 44, loss = 0.28754857
Iteration 45, loss = 0.28446073
Iteration 46, loss = 0.28171291
Iteration 47, loss = 0.27581211
Iteration 48, loss = 0.27501821
Iteration 49, loss = 0.26887711
Iteration 50, loss = 0.26419486
Iteration 51, loss = 0.26008157
Iteration 52, loss = 0.25398451
Iteration 53, loss = 0.24839302
Iteration 54, loss = 0.24870753
Iteration 55, loss = 0.24693347
Iteration 56, loss = 0.24502834
Iteration 57, loss = 0.23933694
Iteration 58, loss = 0.23590469
Iteration 59, loss = 0.22970131
Iteration 60, loss = 0.23161066
Iteration 61, loss = 0.22960016
Iteration 62, loss = 0.22100017
Iteration 63, loss = 0.22177811
Iteration 64, loss = 0.22451561
Iteration 65, loss = 0.22205843
Iteration 66, loss = 0.21939888
Iteration 67, loss = 0.21799980
Iteration 68, loss = 0.21548155
Iteration 69, loss = 0.21288245
Iteration 70, loss = 0.21156165
Iteration 71, loss = 0.21418621
Iteration 72, loss = 0.21018489
Iteration 73, loss = 0.20702838
Iteration 74, loss = 0.20346411
Iteration 75, loss = 0.20356096
Iteration 76, loss = 0.21085453
Iteration 77, loss = 0.20297121
Iteration 78, loss = 0.20682925
Iteration 79, loss = 0.20280356
Iteration 80, loss = 0.20215679
Iteration 81, loss = 0.19955870
Iteration 82, loss = 0.19929434
Iteration 83, loss = 0.20006275
Iteration 84, loss = 0.19741266
Iteration 85, loss = 0.19599048
Iteration 86, loss = 0.19643918
Iteration 87, loss = 0.19518685
Iteration 88, loss = 0.19685479
Iteration 89, loss = 0.19497213
Iteration 90, loss = 0.18987207
Iteration 91, loss = 0.19213220
Iteration 92, loss = 0.19676406
Iteration 93, loss = 0.19307479
Iteration 94, loss = 0.19254119
Iteration 95, loss = 0.18918428
Iteration 96, loss = 0.19028734
Iteration 97, loss = 0.18606298
Iteration 98, loss = 0.18950389
Iteration 99, loss = 0.18351107
Iteration 100, loss = 0.18856617
Iteration 101, loss = 0.18626957
Iteration 102, loss = 0.18861261
Iteration 103, loss = 0.18589004
Iteration 104, loss = 0.18231657
Iteration 105, loss = 0.18517451
Iteration 106, loss = 0.18468357
Iteration 107, loss = 0.18387279
Iteration 108, loss = 0.18306224
Iteration 109, loss = 0.18572714
Iteration 110, loss = 0.18058560
Iteration 111, loss = 0.18093471
Iteration 112, loss = 0.18512552
Iteration 113, loss = 0.18730688
Iteration 114, loss = 0.17962729
Iteration 115, loss = 0.17943530
Iteration 116, loss = 0.17784037
Iteration 117, loss = 0.17746199
Iteration 118, loss = 0.17975688
Iteration 119, loss = 0.17927089
Iteration 120, loss = 0.17692110
Iteration 121, loss = 0.17731153
Iteration 122, loss = 0.17834064
Iteration 123, loss = 0.17471444
Iteration 124, loss = 0.17869968
Iteration 125, loss = 0.17658627
Iteration 126, loss = 0.17468038
Iteration 127, loss = 0.17550595
Iteration 128, loss = 0.17300332
Iteration 129, loss = 0.17461479
Iteration 130, loss = 0.17392362
Iteration 131, loss = 0.17932947
Iteration 132, loss = 0.17774561
Iteration 133, loss = 0.17794180
Iteration 134, loss = 0.17495174
Iteration 135, loss = 0.17372233
Iteration 136, loss = 0.17456126
Iteration 137, loss = 0.17254402
Iteration 138, loss = 0.16885010
Iteration 139, loss = 0.17435419
Iteration 140, loss = 0.17215945
Iteration 141, loss = 0.17354185
Iteration 142, loss = 0.17232474
Iteration 143, loss = 0.17488901
Iteration 144, loss = 0.17043533
Iteration 145, loss = 0.17242162
Iteration 146, loss = 0.17052985
Iteration 147, loss = 0.17130374
Iteration 148, loss = 0.16786748
Iteration 149, loss = 0.16938605
Iteration 150, loss = 0.17319762
Iteration 151, loss = 0.16959787
Iteration 152, loss = 0.17441935
Iteration 153, loss = 0.16805300
Iteration 154, loss = 0.16954482
Iteration 155, loss = 0.17040760
Iteration 156, loss = 0.16825737
Iteration 157, loss = 0.17061424
Iteration 158, loss = 0.17362018
Iteration 159, loss = 0.16768937
Iteration 160, loss = 0.16808361
Iteration 161, loss = 0.17258371
Iteration 162, loss = 0.16760786
Iteration 163, loss = 0.16397313
Iteration 164, loss = 0.17167672
Iteration 165, loss = 0.16777847
Iteration 166, loss = 0.16713476
Iteration 167, loss = 0.16295900
Iteration 168, loss = 0.17031127
Iteration 169, loss = 0.17007355
Iteration 170, loss = 0.16518888
Iteration 171, loss = 0.17043408
Iteration 172, loss = 0.17019941
Iteration 173, loss = 0.16697333
Iteration 174, loss = 0.16641234
Iteration 175, loss = 0.16609694
Iteration 176, loss = 0.16122851
Iteration 177, loss = 0.16003689
Iteration 178, loss = 0.16596750
Iteration 179, loss = 0.16404714
Iteration 180, loss = 0.17171390
Iteration 181, loss = 0.16524560
Iteration 182, loss = 0.16665413
Iteration 183, loss = 0.16845792
Iteration 184, loss = 0.16481969
Iteration 185, loss = 0.16417126
Iteration 186, loss = 0.16682734
Iteration 187, loss = 0.16264579
Iteration 188, loss = 0.16169697
Training loss did not improve more than tol=0.000100 for 10 consecutive epochs. Stopping.

MLPClassifier(hidden_layer_sizes=16, max_iter=500, verbose=True)

In [91]:
y_predict = model.predict(X_test)

In [92]:
from sklearn.metrics import accuracy_score

In [93]:
accuracy = accuracy_score(y_test, y_predict)

In [94]:
accuracy * 100

90.44761904761904