In [67]:
import pandas as pd

In [68]:
df = pd.read_csv("digits.csv")

In [69]:
df.head()

,label,pixel0,pixel1,pixel2,pixel3,pixel4,pixel5,pixel6,pixel7,pixel8,...,pixel774,pixel775,pixel776,pixel777,pixel778,pixel779,pixel780,pixel781,pixel782,pixel783
0,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,4,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [70]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 42000 entries, 0 to 41999
Columns: 785 entries, label to pixel783
dtypes: int64(785)
memory usage: 251.5 MB

In [71]:
df.describe()

,label,pixel0,pixel1,pixel2,pixel3,pixel4,pixel5,pixel6,pixel7,pixel8,...,pixel774,pixel775,pixel776,pixel777,pixel778,pixel779,pixel780,pixel781,pixel782,pixel783
count,42000.000000,42000.0,42000.0,42000.0,42000.0,42000.0,42000.0,42000.0,42000.0,42000.0,...,42000.000000,42000.000000,42000.000000,42000.00000,42000.000000,42000.000000,42000.0,42000.0,42000.0,42000.0
mean,4.456643,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.219286,0.117095,0.059024,0.02019,0.017238,0.002857,0.0,0.0,0.0,0.0
std,2.887730,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,6.312890,4.633819,3.274488,1.75987,1.894498,0.414264,0.0,0.0,0.0,0.0
min,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.0,0.0,0.0,0.0
25%,2.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.0,0.0,0.0,0.0
50%,4.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.0,0.0,0.0,0.0
75%,7.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.0,0.0,0.0,0.0
max,9.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,254.000000,254.000000,253.000000,253.00000,254.000000,62.000000,0.0,0.0,0.0,0.0

In [72]:
df.columns

Index(['label', 'pixel0', 'pixel1', 'pixel2', 'pixel3', 'pixel4', 'pixel5',
       'pixel6', 'pixel7', 'pixel8',
       ...
       'pixel774', 'pixel775', 'pixel776', 'pixel777', 'pixel778', 'pixel779',
       'pixel780', 'pixel781', 'pixel782', 'pixel783'],
      dtype='object', length=785)

In [73]:
X = df[[f"pixel{i}" for i in range(784)]]
y = df["label"]

In [74]:
from sklearn.model_selection import train_test_split

In [75]:
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state = 2529)

In [76]:
from sklearn.neural_network import MLPClassifier

In [ ]:
model = MLPClassifier(hidden_layer_sizes = (8,), max_iter = 500, verbose = True)

In [97]:
model.fit(X_train, y_train)

Iteration 1, loss = 3.29957833
Iteration 2, loss = 2.27807021
Iteration 3, loss = 2.20752966
Iteration 4, loss = 2.17055099
Iteration 5, loss = 2.13995684
Iteration 6, loss = 2.11822255
Iteration 7, loss = 2.09605082
Iteration 8, loss = 2.06104462
Iteration 9, loss = 2.00569064
Iteration 10, loss = 1.95136472
Iteration 11, loss = 1.91440013
Iteration 12, loss = 1.88472220
Iteration 13, loss = 1.85922679
Iteration 14, loss = 1.82865688
Iteration 15, loss = 1.81176136
Iteration 16, loss = 1.79842091
Iteration 17, loss = 1.78756825
Iteration 18, loss = 1.77629503
Iteration 19, loss = 1.76644213
Iteration 20, loss = 1.75493889
Iteration 21, loss = 1.74819044
Iteration 22, loss = 1.73442851
Iteration 23, loss = 1.73147608
Iteration 24, loss = 1.72114566
Iteration 25, loss = 1.71155419
Iteration 26, loss = 1.71248805
Iteration 27, loss = 1.70191392
Iteration 28, loss = 1.69950187
Iteration 29, loss = 1.69468500
Iteration 30, loss = 1.69178094
Iteration 31, loss = 1.68478991
Iteration 32, loss = 1.68084513
Iteration 33, loss = 1.67851540
Iteration 34, loss = 1.67614653
Iteration 35, loss = 1.67383032
Iteration 36, loss = 1.66868889
Iteration 37, loss = 1.66587586
Iteration 38, loss = 1.66161966
Iteration 39, loss = 1.66434620
Iteration 40, loss = 1.65558605
Iteration 41, loss = 1.66332203
Iteration 42, loss = 1.65243911
Iteration 43, loss = 1.64749153
Iteration 44, loss = 1.64418261
Iteration 45, loss = 1.64191366
Iteration 46, loss = 1.63852529
Iteration 47, loss = 1.63314118
Iteration 48, loss = 1.62965511
Iteration 49, loss = 1.62918468
Iteration 50, loss = 1.62555279
Iteration 51, loss = 1.62117685
Iteration 52, loss = 1.61923825
Iteration 53, loss = 1.61437650
Iteration 54, loss = 1.61089057
Iteration 55, loss = 1.60759791
Iteration 56, loss = 1.60607972
Iteration 57, loss = 1.60159138
Iteration 58, loss = 1.59498021
Iteration 59, loss = 1.59584703
Iteration 60, loss = 1.59444041
Iteration 61, loss = 1.59052017
Iteration 62, loss = 1.48038180
Iteration 63, loss = 1.37352363
Iteration 64, loss = 1.24293944
Iteration 65, loss = 1.17382998
Iteration 66, loss = 1.15312482
Iteration 67, loss = 1.12854010
Iteration 68, loss = 1.11152015
Iteration 69, loss = 1.09951742
Iteration 70, loss = 1.08186171
Iteration 71, loss = 1.07858328
Iteration 72, loss = 1.06985542
Iteration 73, loss = 1.06418991
Iteration 74, loss = 1.06086825
Iteration 75, loss = 1.05753237
Iteration 76, loss = 1.05278281
Iteration 77, loss = 1.05579839
Iteration 78, loss = 1.04842593
Iteration 79, loss = 1.04813324
Iteration 80, loss = 1.04285177
Iteration 81, loss = 1.04347247
Iteration 82, loss = 1.03997895
Iteration 83, loss = 1.04043996
Iteration 84, loss = 1.03708093
Iteration 85, loss = 1.03942167
Iteration 86, loss = 1.03866436
Iteration 87, loss = 1.03871974
Iteration 88, loss = 1.03291550
Iteration 89, loss = 1.03524119
Iteration 90, loss = 1.03343975
Iteration 91, loss = 1.03350710
Iteration 92, loss = 1.03086738
Iteration 93, loss = 1.03852290
Iteration 94, loss = 1.02843747
Iteration 95, loss = 1.02874090
Iteration 96, loss = 1.02822164
Iteration 97, loss = 1.02928241
Iteration 98, loss = 1.02722421
Iteration 99, loss = 1.03212558
Iteration 100, loss = 1.02868181
Iteration 101, loss = 1.02810187
Iteration 102, loss = 1.02614098
Iteration 103, loss = 1.02784318
Iteration 104, loss = 1.02781374
Iteration 105, loss = 1.02904039
Iteration 106, loss = 1.02454006
Iteration 107, loss = 1.02737758
Iteration 108, loss = 1.03135698
Iteration 109, loss = 1.02874117
Iteration 110, loss = 1.02361663
Iteration 111, loss = 1.02146687
Iteration 112, loss = 1.02575074
Iteration 113, loss = 1.02314803
Iteration 114, loss = 1.02256647
Iteration 115, loss = 1.02505727
Iteration 116, loss = 1.02319364
Iteration 117, loss = 1.02606969
Iteration 118, loss = 1.02336423
Iteration 119, loss = 1.02272319
Iteration 120, loss = 1.02595311
Iteration 121, loss = 1.02090626
Iteration 122, loss = 1.02828199
Iteration 123, loss = 1.02111552
Iteration 124, loss = 1.02460605
Iteration 125, loss = 1.02172830
Iteration 126, loss = 1.02271942
Iteration 127, loss = 1.01850765
Iteration 128, loss = 1.02537624
Iteration 129, loss = 1.02377509
Iteration 130, loss = 1.02438782
Iteration 131, loss = 1.02236280
Iteration 132, loss = 1.01938023
Iteration 133, loss = 1.02233996
Iteration 134, loss = 1.02007829
Iteration 135, loss = 1.02187125
Iteration 136, loss = 1.02010367
Iteration 137, loss = 1.01985718
Iteration 138, loss = 1.02511838
Training loss did not improve more than tol=0.000100 for 10 consecutive epochs. Stopping.

MLPClassifier(hidden_layer_sizes=8, max_iter=500, verbose=True)

In [98]:
y_predict = model.predict(X_test)

In [99]:
from sklearn.metrics import accuracy_score

In [100]:
accuracy = accuracy_score(y_test, y_predict)

In [101]:
accuracy * 100

64.45714285714286