In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("digits.csv")

In [3]:
df.head()

,label,pixel0,pixel1,pixel2,pixel3,pixel4,pixel5,pixel6,pixel7,pixel8,...,pixel774,pixel775,pixel776,pixel777,pixel778,pixel779,pixel780,pixel781,pixel782,pixel783
0,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,4,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 42000 entries, 0 to 41999
Columns: 785 entries, label to pixel783
dtypes: int64(785)
memory usage: 251.5 MB

In [5]:
df.describe()

,label,pixel0,pixel1,pixel2,pixel3,pixel4,pixel5,pixel6,pixel7,pixel8,...,pixel774,pixel775,pixel776,pixel777,pixel778,pixel779,pixel780,pixel781,pixel782,pixel783
count,42000.000000,42000.0,42000.0,42000.0,42000.0,42000.0,42000.0,42000.0,42000.0,42000.0,...,42000.000000,42000.000000,42000.000000,42000.00000,42000.000000,42000.000000,42000.0,42000.0,42000.0,42000.0
mean,4.456643,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.219286,0.117095,0.059024,0.02019,0.017238,0.002857,0.0,0.0,0.0,0.0
std,2.887730,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,6.312890,4.633819,3.274488,1.75987,1.894498,0.414264,0.0,0.0,0.0,0.0
min,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.0,0.0,0.0,0.0
25%,2.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.0,0.0,0.0,0.0
50%,4.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.0,0.0,0.0,0.0
75%,7.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.0,0.0,0.0,0.0
max,9.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,254.000000,254.000000,253.000000,253.00000,254.000000,62.000000,0.0,0.0,0.0,0.0

In [6]:
df.columns

Index(['label', 'pixel0', 'pixel1', 'pixel2', 'pixel3', 'pixel4', 'pixel5',
       'pixel6', 'pixel7', 'pixel8',
       ...
       'pixel774', 'pixel775', 'pixel776', 'pixel777', 'pixel778', 'pixel779',
       'pixel780', 'pixel781', 'pixel782', 'pixel783'],
      dtype='object', length=785)

In [7]:
X = df[[f"pixel{i}" for i in range(784)]]
y = df["label"]

In [8]:
from sklearn.model_selection import train_test_split

In [9]:
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state = 2529)

In [10]:
from sklearn.neural_network import MLPClassifier

In [11]:
model = MLPClassifier(hidden_layer_sizes = (128,), max_iter = 500, verbose = True)

In [12]:
model.fit(X_train, y_train)

Iteration 1, loss = 4.38338219
Iteration 2, loss = 1.55955654
Iteration 3, loss = 0.93240799
Iteration 4, loss = 0.64414234
Iteration 5, loss = 0.48705682
Iteration 6, loss = 0.36043039
Iteration 7, loss = 0.28676350
Iteration 8, loss = 0.21804744
Iteration 9, loss = 0.19385512
Iteration 10, loss = 0.14087758
Iteration 11, loss = 0.13609074
Iteration 12, loss = 0.12401582
Iteration 13, loss = 0.11728512
Iteration 14, loss = 0.12849705
Iteration 15, loss = 0.11646768
Iteration 16, loss = 0.13980020
Iteration 17, loss = 0.11443659
Iteration 18, loss = 0.10895793
Iteration 19, loss = 0.11404397
Iteration 20, loss = 0.12377186
Iteration 21, loss = 0.13468293
Iteration 22, loss = 0.18508430
Iteration 23, loss = 0.11713917
Iteration 24, loss = 0.10973118
Iteration 25, loss = 0.08424452
Iteration 26, loss = 0.10798458
Iteration 27, loss = 0.08089104
Iteration 28, loss = 0.07198783
Iteration 29, loss = 0.10389781
Iteration 30, loss = 0.10698144
Iteration 31, loss = 0.10297871
Iteration 32, loss = 0.08571947
Iteration 33, loss = 0.12652148
Iteration 34, loss = 0.08959845
Iteration 35, loss = 0.06760472
Iteration 36, loss = 0.08383249
Iteration 37, loss = 0.10096295
Iteration 38, loss = 0.09832008
Iteration 39, loss = 0.08698055
Iteration 40, loss = 0.07112933
Iteration 41, loss = 0.06551972
Iteration 42, loss = 0.08430528
Iteration 43, loss = 0.08555934
Iteration 44, loss = 0.07103713
Iteration 45, loss = 0.07558520
Iteration 46, loss = 0.09262420
Iteration 47, loss = 0.11647765
Iteration 48, loss = 0.11400781
Iteration 49, loss = 0.08329245
Iteration 50, loss = 0.07291548
Iteration 51, loss = 0.04493799
Iteration 52, loss = 0.03946229
Iteration 53, loss = 0.05919892
Iteration 54, loss = 0.09296600
Iteration 55, loss = 0.08299756
Iteration 56, loss = 0.09961683
Iteration 57, loss = 0.04887804
Iteration 58, loss = 0.05639853
Iteration 59, loss = 0.05631772
Iteration 60, loss = 0.07185978
Iteration 61, loss = 0.08589644
Iteration 62, loss = 0.08101457
Iteration 63, loss = 0.05393239
Training loss did not improve more than tol=0.000100 for 10 consecutive epochs. Stopping.

MLPClassifier(hidden_layer_sizes=(128,), max_iter=500, verbose=True)

In [13]:
y_predict = model.predict(X_test)

In [14]:
from sklearn.metrics import accuracy_score

In [15]:
accuracy = accuracy_score(y_test, y_predict)

In [16]:
accuracy * 100

96.82857142857144