In [51]:
import pandas as pd

In [52]:
df = pd.read_csv("digits.csv")

In [53]:
df.head()

,label,pixel0,pixel1,pixel2,pixel3,pixel4,pixel5,pixel6,pixel7,pixel8,...,pixel774,pixel775,pixel776,pixel777,pixel778,pixel779,pixel780,pixel781,pixel782,pixel783
0,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,4,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [54]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 42000 entries, 0 to 41999
Columns: 785 entries, label to pixel783
dtypes: int64(785)
memory usage: 251.5 MB

In [55]:
df.describe()

,label,pixel0,pixel1,pixel2,pixel3,pixel4,pixel5,pixel6,pixel7,pixel8,...,pixel774,pixel775,pixel776,pixel777,pixel778,pixel779,pixel780,pixel781,pixel782,pixel783
count,42000.000000,42000.0,42000.0,42000.0,42000.0,42000.0,42000.0,42000.0,42000.0,42000.0,...,42000.000000,42000.000000,42000.000000,42000.00000,42000.000000,42000.000000,42000.0,42000.0,42000.0,42000.0
mean,4.456643,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.219286,0.117095,0.059024,0.02019,0.017238,0.002857,0.0,0.0,0.0,0.0
std,2.887730,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,6.312890,4.633819,3.274488,1.75987,1.894498,0.414264,0.0,0.0,0.0,0.0
min,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.0,0.0,0.0,0.0
25%,2.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.0,0.0,0.0,0.0
50%,4.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.0,0.0,0.0,0.0
75%,7.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.0,0.0,0.0,0.0
max,9.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,254.000000,254.000000,253.000000,253.00000,254.000000,62.000000,0.0,0.0,0.0,0.0

In [56]:
df.columns

Index(['label', 'pixel0', 'pixel1', 'pixel2', 'pixel3', 'pixel4', 'pixel5',
       'pixel6', 'pixel7', 'pixel8',
       ...
       'pixel774', 'pixel775', 'pixel776', 'pixel777', 'pixel778', 'pixel779',
       'pixel780', 'pixel781', 'pixel782', 'pixel783'],
      dtype='object', length=785)

In [57]:
X = df[[f"pixel{i}" for i in range(784)]]
y = df["label"]

In [58]:
from sklearn.model_selection import train_test_split

In [59]:
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state = 2529)

In [60]:
from sklearn.neural_network import MLPClassifier

In [61]:
model = MLPClassifier(hidden_layer_sizes = (784, 512, 256, 128, 64), max_iter = 500, verbose = True)

In [62]:
model.fit(X_train, y_train)

Iteration 1, loss = 1.25135641
Iteration 2, loss = 0.16579768
Iteration 3, loss = 0.09699479
Iteration 4, loss = 0.07522812
Iteration 5, loss = 0.05614431
Iteration 6, loss = 0.03751602
Iteration 7, loss = 0.02917975
Iteration 8, loss = 0.04458550
Iteration 9, loss = 0.04338094
Iteration 10, loss = 0.03442656
Iteration 11, loss = 0.04011985
Iteration 12, loss = 0.04501380
Iteration 13, loss = 0.03669669
Iteration 14, loss = 0.04799559
Iteration 15, loss = 0.03940229
Iteration 16, loss = 0.02950369
Iteration 17, loss = 0.02184028
Iteration 18, loss = 0.02617578
Iteration 19, loss = 0.02307033
Iteration 20, loss = 0.02696449
Iteration 21, loss = 0.04220717
Iteration 22, loss = 0.03311520
Iteration 23, loss = 0.03120775
Iteration 24, loss = 0.02517266
Iteration 25, loss = 0.02964868
Iteration 26, loss = 0.01915214
Iteration 27, loss = 0.02634832
Iteration 28, loss = 0.01802384
Iteration 29, loss = 0.02775932
Iteration 30, loss = 0.02697576
Iteration 31, loss = 0.01174782
Iteration 32, loss = 0.02419824
Iteration 33, loss = 0.03228139
Iteration 34, loss = 0.02606713
Iteration 35, loss = 0.02510767
Iteration 36, loss = 0.01774706
Iteration 37, loss = 0.01170874
Iteration 38, loss = 0.01527511
Iteration 39, loss = 0.01741082
Iteration 40, loss = 0.02176978
Iteration 41, loss = 0.01899214
Iteration 42, loss = 0.01475084
Training loss did not improve more than tol=0.000100 for 10 consecutive epochs. Stopping.

MLPClassifier(hidden_layer_sizes=(784, 512, 256, 128, 64), max_iter=500,
              verbose=True)

In [63]:
y_predict = model.predict(X_test)

In [64]:
from sklearn.metrics import accuracy_score

In [65]:
accuracy = accuracy_score(y_test, y_predict)

In [66]:
accuracy * 100

97.45714285714286