In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("diabetes_dataset.csv")

In [3]:
df.head()

,Age,Pregnancies,BMI,Glucose,BloodPressure,HbA1c,LDL,HDL,Triglycerides,WaistCircumference,HipCircumference,WHR,FamilyHistory,DietType,Hypertension,MedicationUse,Outcome
0,69,5,28.39,130.1,77.0,5.4,130.4,44.0,50.0,90.5,107.9,0.84,0,0,0,1,0
1,32,1,26.49,116.5,72.0,4.5,87.4,54.2,129.9,113.3,81.4,1.39,0,0,0,0,0
2,89,13,25.34,101.0,82.0,4.9,112.5,56.8,177.6,84.7,107.2,0.79,0,0,0,1,0
3,78,13,29.91,146.0,104.0,5.7,50.7,39.1,117.0,108.9,110.0,0.99,0,0,0,1,1
4,38,8,24.56,103.2,74.0,4.7,102.5,29.1,145.9,84.1,92.8,0.91,0,1,0,0,0

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9538 entries, 0 to 9537
Data columns (total 17 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Age                 9538 non-null   int64
 1   Pregnancies         9538 non-null   int64
 2   BMI                 9538 non-null   float64
 3   Glucose             9538 non-null   float64
 4   BloodPressure       9538 non-null   float64
 5   HbA1c               9538 non-null   float64
 6   LDL                 9538 non-null   float64
 7   HDL                 9538 non-null   float64
 8   Triglycerides       9538 non-null   float64
 9   WaistCircumference  9538 non-null   float64
 10  HipCircumference    9538 non-null   float64
 11  WHR                 9538 non-null   float64
 12  FamilyHistory       9538 non-null   int64
 13  DietType            9538 non-null   int64
 14  Hypertension        9538 non-null   int64
 15  MedicationUse       9538 non-null   int64
 16  Outcome             9538 non-null   int64
dtypes: float64(10), int64(7)
memory usage: 1.2 MB

In [5]:
df.describe()

,Age,Pregnancies,BMI,Glucose,BloodPressure,HbA1c,LDL,HDL,Triglycerides,WaistCircumference,HipCircumference,WHR,FamilyHistory,DietType,Hypertension,MedicationUse,Outcome
count,9538.000000,9538.000000,9538.000000,9538.000000,9538.000000,9538.000000,9538.000000,9538.000000,9538.000000,9538.000000,9538.000000,9538.000000,9538.000000,9538.000000,9538.000000,9538.000000,9538.000000
mean,53.577584,7.986161,27.052364,106.104183,84.475781,4.650661,100.133456,49.953418,151.147746,93.951678,103.060621,0.917400,0.302474,0.486161,0.001048,0.405012,0.344097
std,20.764651,4.933469,5.927955,21.918590,14.123480,0.476395,29.911910,15.242194,48.951627,15.594468,13.438827,0.140828,0.459354,0.661139,0.032364,0.490920,0.475098
min,18.000000,0.000000,15.000000,50.000000,60.000000,4.000000,-12.000000,-9.200000,50.000000,40.300000,54.800000,0.420000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,36.000000,4.000000,22.870000,91.000000,74.000000,4.300000,80.100000,39.700000,117.200000,83.400000,94.000000,0.820000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,53.000000,8.000000,27.050000,106.000000,84.000000,4.600000,99.900000,50.200000,150.550000,93.800000,103.200000,0.910000,0.000000,0.000000,0.000000,0.000000,0.000000
75%,72.000000,12.000000,31.180000,121.000000,94.000000,5.000000,120.200000,60.200000,185.100000,104.600000,112.100000,1.010000,1.000000,1.000000,0.000000,1.000000,1.000000
max,89.000000,16.000000,49.660000,207.200000,138.000000,6.900000,202.200000,107.800000,345.800000,163.000000,156.600000,1.490000,1.000000,2.000000,1.000000,1.000000,1.000000

In [6]:
df.columns

Index(['Age', 'Pregnancies', 'BMI', 'Glucose', 'BloodPressure', 'HbA1c', 'LDL',
       'HDL', 'Triglycerides', 'WaistCircumference', 'HipCircumference', 'WHR',
       'FamilyHistory', 'DietType', 'Hypertension', 'MedicationUse',
       'Outcome'],
      dtype='object')

In [7]:
X = df[['Age', 'Pregnancies', 'BMI', 'Glucose', 'BloodPressure', 'HbA1c', 'LDL',
       'HDL', 'Triglycerides', 'WaistCircumference', 'HipCircumference', 'WHR',
       'FamilyHistory', 'DietType', 'Hypertension', 'MedicationUse']]
y = df['Outcome']

In [8]:
from sklearn.model_selection import train_test_split

In [9]:
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state = 2529)

In [26]:
from sklearn.neural_network import MLPClassifier

In [27]:
model = MLPClassifier(hidden_layer_sizes = (8,), max_iter = 500)

In [28]:
model.fit(X_train, y_train)

MLPClassifier(hidden_layer_sizes=(8,), max_iter=500)

In [29]:
y_predict = model.predict(X_test)

In [30]:
from sklearn.metrics import accuracy_score

In [31]:
accuracy = accuracy_score(y_test, y_predict)

In [32]:
accuracy * 100

97.19077568134172

In [33]:
weights = list(model.coefs_)
for weight in weights[0]:
    for w in weight:
        print(w, end=" ")
    print()

print()
for weight in weights[1]:
    for w in weight:
        print(w, end=" ")
    print()

-0.3242510558147486 0.12655566443473004 -0.004771719401820615 0.17216194685830813 0.5551797914182061 -6.586107433527591e-206 0.20037367361411088 -0.11378369062865211
0.1769243046151022 0.24870170371776837 -0.09140676257274621 0.6110806665678201 0.1444919093761449 7.432056683337558e-226 -0.07827957631015169 -0.09516501245722665
0.06307548765570782 0.4357561225867906 0.11560565523669 0.27763487253925534 0.4606423613872213 -3.2881756118508694e-249 -0.15819911353835311 -0.4975129561488448
0.29339380372510493 0.09226139878411964 -0.0043408084442529 -0.15568176609703602 -0.14522168000564892 9.573442989982262e-195 0.36872301314605416 -0.26522656506455067
0.3564517316336499 0.009525227658583475 -0.16660115665849493 -0.0353789811522606 -0.4582063153895533 -5.670966794956836e-218 -0.43784223768887337 -0.24007010110876342
-0.74105227512651 0.842277676308044 -0.6904177018976773 0.2614526935935338 0.10293061618489169 2.448367798416565e-252 0.0677522112788574 -0.22192646312646216
0.35713737413364255 0.41357221117666865 -0.10285540886431652 0.2990730874138278 -0.08688680748189083 -4.2788334660503856e-252 -0.3985473823457091 0.05448562854799663
0.0634870630901825 -0.029802515599247285 -0.007712884801281088 0.3946333402548661 0.04817667642873306 -1.088368369768979e-200 -0.18250621799729705 -0.35960731638711
-0.2361664959899506 -0.14555014439521854 0.20394913214212212 -0.038464143336573296 0.11662867485219014 -3.3671896048039994e-217 0.1978657768388047 0.21184358545776674
-0.09370707935382674 0.04466875320233071 -0.012961972870514791 0.4040042018023017 0.3193353414040129 -1.728304200174073e-254 -0.45306231958792875 -0.21541974619958668
0.22617346934887808 0.713537277375507 0.30337183067407986 0.5833818606558113 0.08080919712787339 2.111629756324304e-219 -0.17022277321549475 0.11283300454408096
-0.6953946361283773 1.291744466686467 -1.2312943070526594 1.0521919398157893 -0.5619805136617472 6.098824551333599e-227 0.07349427262646564 -0.0205942071890068
6.264015183200815 -5.913867535380686 7.2476859656489525 -6.639067929027494 6.827026981220227 -1.5435112912532048e-264 -1.0999100499803705e-182 -0.0026204188119350897
0.3170909455278062 0.17256608782915553 -0.5277797684231135 0.1506869924384621 -0.22682316230219202 1.0103233919761595e-196 0.17431515928310048 -0.22687295440490646
0.8102115184498775 -0.968404658204403 1.0036553203153409 -1.4544740609104476 1.460999876103061 -1.9524355391051868e-213 2.3577031354631443e-204 -1.6150240519865736e-196
0.5297832090527541 -0.21099439543616505 0.7822897646122771 -0.9090753970803999 0.4239989784995518 1.1766688615394281e-217 0.22959006368794954 0.11593411113310215

0.8238110231324088
-0.3330973534530119
0.3063994370058112
-0.27315223844790437
0.5988041800506132
-4.047637787300132e-168
0.5141061411279473
-0.18157905970666469