In [19]:
import pandas as pd

In [20]:
df = pd.read_csv(r"C:\Users\Dell\Desktop\Python_Tutorials\AIML_Lab\Lab_Assignment_2\Linear_Regression (From Scratch)\SOCR-HeightWeight.csv")

In [21]:
df.head()

   Index  Height(Inches)  Weight(Pounds)
0      1        65.78331        112.9925
1      2        71.51521        136.4873
2      3        69.39874        153.0269
3      4        68.21660        142.3354
4      5        67.78781        144.2971

In [22]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 25000 entries, 0 to 24999
Data columns (total 3 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Index           25000 non-null  int64
 1   Height(Inches)  25000 non-null  float64
 2   Weight(Pounds)  25000 non-null  float64
dtypes: float64(2), int64(1)
memory usage: 586.1 KB

In [23]:
df.describe()

              Index  Height(Inches)  Weight(Pounds)
count  25000.000000    25000.000000    25000.000000
mean   12500.500000       67.993114      127.079421
std     7217.022701        1.901679       11.660898
min        1.000000       60.278360       78.014760
25%     6250.750000       66.704397      119.308675
50%    12500.500000       67.995700      127.157750
75%    18750.250000       69.272958      134.892850
max    25000.000000       75.152800      170.924000

In [24]:
df.columns

Index(['Index', 'Height(Inches)', 'Weight(Pounds)'], dtype='object')

In [25]:
X = df[['Height(Inches)']]
y = df['Weight(Pounds)']

In [26]:
from sklearn.model_selection import train_test_split

In [27]:
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state = 2529)

In [30]:
from sklearn.linear_model import SGDRegressor

In [35]:
model = SGDRegressor(max_iter = 5000)

In [36]:
model.fit(X_train, y_train)

SGDRegressor(max_iter=5000)

In [37]:
y_predict = model.predict(X_test)

In [38]:
from sklearn.metrics import mean_absolute_percentage_error

In [39]:
error = mean_absolute_percentage_error(y_test, y_predict)

In [40]:
accuracy = 100 - error

In [41]:
accuracy

-13450.756881888965