In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("https://raw.githubusercontent.com/YBI-Foundation/Dataset/main/Customer%20Purchase.csv")

In [3]:
df.head()

   Customer ID  Age  Gender Education   Review Purchased
0         1021   30  Female    School  Average        No
1         1022   68  Female        UG     Poor        No
2         1023   70  Female        PG     Good        No
3         1024   72  Female        PG     Good        No
4         1025   16  Female        UG  Average        No

In [4]:
# df["Education"].unique()
df["Review"].unique()
# df["Purchased"].unique()

array(['Average', 'Poor', 'Good'], dtype=object)

In [5]:
df["Education"] = df["Education"].replace({"School" : 0, "UG" : 1, "PG" : 2})

C:\Users\Dell\AppData\Local\Temp\ipykernel_15244\2008185804.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df["Education"] = df["Education"].replace({"School" : 0, "UG" : 1, "PG" : 2})

In [6]:
df["Review"] = df["Review"].replace({"Poor" : 0, "Average" : 1, "Good" : 2})

C:\Users\Dell\AppData\Local\Temp\ipykernel_15244\575923764.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df["Review"] = df["Review"].replace({"Poor" : 0, "Average" : 1, "Good" : 2})

In [7]:
df["Gender"] = df["Gender"].replace({"Male" : 0, "Female" : 1})

C:\Users\Dell\AppData\Local\Temp\ipykernel_15244\3785326694.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df["Gender"] = df["Gender"].replace({"Male" : 0, "Female" : 1})

In [8]:
df.head()

   Customer ID  Age  Gender  Education  Review Purchased
0         1021   30       1          0       1        No
1         1022   68       1          1       0        No
2         1023   70       1          2       2        No
3         1024   72       1          2       2        No
4         1025   16       1          1       1        No

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 6 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Customer ID  50 non-null     int64
 1   Age          50 non-null     int64
 2   Gender       50 non-null     int64
 3   Education    50 non-null     int64
 4   Review       50 non-null     int64
 5   Purchased    50 non-null     object
dtypes: int64(5), object(1)
memory usage: 2.5+ KB

In [10]:
df.describe()

       Customer ID        Age     Gender  Education     Review
count     50.00000  50.000000  50.000000  50.000000  50.000000
mean    1045.50000  54.160000   0.580000   1.040000   1.000000
std       14.57738  25.658161   0.498569   0.832013   0.857143
min     1021.00000  15.000000   0.000000   0.000000   0.000000
25%     1033.25000  30.250000   0.000000   0.000000   0.000000
50%     1045.50000  57.000000   1.000000   1.000000   1.000000
75%     1057.75000  74.000000   1.000000   2.000000   2.000000
max     1070.00000  98.000000   1.000000   2.000000   2.000000

In [11]:
df.columns

Index(['Customer ID', 'Age', 'Gender', 'Education', 'Review', 'Purchased'], dtype='object')

In [12]:
X = df[['Age', 'Gender', 'Education', 'Review']]
y = df['Purchased']

In [13]:
from sklearn.model_selection import train_test_split

In [14]:
X_train, X_test, y_train, y_test = train_test_split(X, y, train_size = 0.8, random_state = 2529)

In [15]:
from sklearn.tree import DecisionTreeClassifier

In [16]:
model_c45 = DecisionTreeClassifier(criterion='entropy', min_samples_split=5, min_impurity_decrease=0.01)

In [17]:
model_c45.fit(X_train, y_train)

DecisionTreeClassifier(criterion='entropy', min_impurity_decrease=0.01,
                       min_samples_split=5)

In [18]:
y_predict = model_c45.predict(X_test)

In [19]:
from sklearn.metrics import accuracy_score

In [20]:
accuracy = accuracy_score(y_test, y_predict)

In [21]:
accuracy * 100

60.0